POST http://217.196.48.228:8080/api/product
content-type: application/json
accept: application/json

{
  "name": "Macbook",
  "description": "Ini Mac",
  "price": "140000"
}

####

GET http://localhost:8080/api/products

###

GET http://localhost:8080/api/product/6

###

GET http://localhost:8080/api/csv/product2024-01-31_18-36-35.csv

###

DELETE http://localhost:8080/api/csv/123.csv



